In [1]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

In [2]:
#define data
data = asarray([['red'], ['green'], ['blue']])
print(data)

[['red']
 ['green']
 ['blue']]


In [3]:
# define one hot encoding
encoder = OneHotEncoder(sparse_output = False)

In [4]:
# transfer data
onehot = encoder.fit_transform(data)
print(onehot)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
